include "/stdlib/jdk/17/openjdk.conf"  

include "#!=app.version mvn -q help:evaluate -Dexpression=project.version -DforceStdout"  
#include "#!=javafx.version mvn -q help:evaluate -Dexpression=openjfx.version -DforceStdout"
javafx.version  = 17
include required("/stdlib/jvm/javafx/from-jmods.conf")


conveyor.billing-email = "nmrview@mac.com"
app.site.base-url = "https://github.com/nanalysis/nmrfx"
app {
    display-name = NMRFx  
    vendor = BruceJohnsonLab
    version = 1.0
    rdns-name = org.nmrfx

    inputs += nmrfx-analyst-gui/target/nmrfx-analyst-gui-11.4.10-SNAPSHOT.jar 
    inputs += nmrfx-analyst-gui/target/classpath-jars

    site.base-url = localhost

  jvm {
    gui.main-class = org.nmrfx.analyst.gui.AnalystApp
    modules = [ javafx.base, javafx.controls, javafx.graphics, javafx.fxml]
  }
}

conveyor.compatibility-level = 15

