import os
from pyproc import *
procOpts(nprocess=7)
FIDHOME, TMPHOME = getTestLocations()
FID(os.path.join(FIDHOME,'bruker/gb1_tract1d/6'))
CREATE(os.path.join(TMPHOME,'tst_gb1_tract1d.nv'))
acqOrder('21')
acqarray(0,0)
fixdsp(True)
skip(0,0)
label('1H','15N')
acqsize(0,0)
tdsize(0,0)
sf('SFO1,1','SFO1,2')
sw('SW_h,1','SW_h,2')
ref('','N')
DIM(1)
SB()
ZF()
FT()
PHASE(ph0=-63.3,ph1=0.0,dimag=False)
run()
