import os
from pyproc import *
FIDHOME, TMPHOME = getTestLocations()
FID(os.path.join(FIDHOME,'bruker/hnconus/7'))
CREATE(os.path.join(TMPHOME,'tst_hnconus_nesta.nv'))

acqOrder('321')
skip(0,0,0)
label('1H','15N','13C')
acqsize(0,0,0)
tdsize(0,0,0)
sf('SFO1,1','SFO1,2','SFO1,3')
sw('SW_h,1','SW_h,2','SW_h,3')
ref('h2o','N','C')
DIM(1)
SB()
ZF()
FT()
PHASE(ph0=-202.8,ph1=0.0,dimag=True)
EXTRACT(start=239,end=653,mode='region')
DIM(2,3)
NESTA()
DIM(2)
SB(c=0.5)
ZF()
FT(negatePairs=True,negateImag=True)
PHASE(ph0=0.0,ph1=0.0,dimag=True)
DIM(3)
SB(c=0.5)
ZF()
FT(negatePairs=True,negateImag=True)
PHASE(ph0=0.0,ph1=0.0,dimag=True)
EXTRACT(start=8,end=120,mode='region')
run()
