import os
from pyproc import *
procOpts(nprocess=7)

FIDHOME, TMPHOME = getTestLocations()
FID(os.path.join(FIDHOME,'rs2d/2Dhetero/688/data.dat'))
CREATE(os.path.join(TMPHOME,'tst_rs2d_2dhetero/Proc/1/data.dat'))

acqOrder('1')
acqarray(0,0)
fixdsp(True)
skip(0,0)
label('1H','1H_2')
acqsize(0,0)
tdsize(0,0)
sf('BASE_FREQ_1','BASE_FREQ_1')
sw('SPECTRAL_WIDTH','SPECTRAL_WIDTH_2D')
ref('','H')
DIM(1)
TDCOMB(coef='echo-antiecho')
SB()
ZF()
FT()
PHASE(ph0=-70.5,ph1=-91.2,dimag=False)
DIM(2)
SB(c=0.5)
ZF()
FT(negateImag=True)
MAG()
run()
