from pyproc import *
procOpts(nprocess=1)

FIDHOME, TMPHOME = getTestLocations()
FID(os.path.join(FIDHOME,'agilent/15Nhsqc.fid'))
CREATE(os.path.join(TMPHOME,'tst_ubiq_hsqc_sf.ucsf'))

label('1H','15N')
sf('sfrq','dfrq2')
sw('sw','sw1')
ref(7.5,'N')
DIM(1)
TDCOMB(coef='echo-antiecho')
SB()
ZF()
FT()
PHASE(ph0=-44.4,ph1=0.0, dimag=True)
EXTRACT(start=40,end=900,mode='region')
DIM(2)
SB(c=0.5)
ZF()
FT(negateImag=True)
PHASE(ph0=0.0,ph1=0.0, dimag=True)
run()
