import os
from pyproc import *
procOpts(nprocess=7)
FIDHOME, TMPHOME = getTestLocations()
FID(os.path.join(FIDHOME,'bruker/ubiq_t1/3'))
CREATE(os.path.join(TMPHOME,'tst_ubiq_t1.nv'))

acqOrder('312')
label('1H','15N','1H_3')
sf('SFO1,1','SFO1,2','SFO1,3')
sw('SW_h,1','SW_h,2','SW_h,3')
ref('h2o','N','H')
DIM(1)
TDCOMB(dim=2,coef='echo-antiecho-r')
SB()
ZF()
FT()
PHASE(ph0=-27.8,ph1=0.0,dimag=False)
EXTRACT(start=53,end=438,mode='region')
DIM(2)
SB(c=0.5)
ZF()
FT(negateImag=True)
PHASE(ph0=0.0,ph1=0.0)
run()
