import os
from pyproc import *
procOpts(nprocess=7)

FIDHOME, TMPHOME = getTestLocations()
FID(os.path.join(FIDHOME,'bruker/ubiq_t2/5'))
CREATE(os.path.join(TMPHOME,'tst_ubiq_t2.nv'))

acqOrder('312')
acqarray(0,0,0)
fixdsp(True)
skip(0,0,0)
label('1H','15N','1H_3')
acqsize(0,0,0)
tdsize(0,0,0)
sf('SFO1,1','SFO1,2','SFO1,3')
sw('SW_h,1','SW_h,2','SW_h,3')
ref('H2O','N','H')
DIM(1)
TDCOMB(coef='echo-antiecho-r')
SB()
ZF()
FT()
PHASE(ph0=132.1,ph1=8.9)
EXTRACT(start=51,end=455,mode='region')
DIM(2)
SB(c=0.5)
ZF()
FT(negateImag=True)
run()
