#!/bin/sh

# nmrfxa [ script  [ arg ... ] ]
# 
# optional environment variables:
#
# JAVA_HOME  - directory of JDK/JRE, if not set then 'java' must be found on PATH
# CLASSPATH  - colon separated list of additional jar files & class directories
# JAVA_OPTS  - list of JVM options, e.g. "-Xmx256m -Dfoo=bar"
#
LOG_CONFIG="-Dlogback.configurationFile=config/logback.xml"

if [ -n "$NMRFXP_MEMORY" ] ; then
    HEAP_MEM=$NMRFXP_MEMORY
else
    HEAP_MEM="2048"
fi

nvjver=${project.version}
nvjmain=org.python.util.jython
nmrfxlib="nmrfx-analyst-$nvjver.jar"

JAVA=java

# get the directory path of this script
# resolve script symlink, if any
pgm="$0"
while [ -h "$pgm" ]; do
    ls=`ls -ld "$pgm"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        pgm="$link"
    else
        pgm=`dirname "$PRG"`/"$link"
    fi
done

dir=`dirname "$pgm"`
CLASSPATH="${dir}/lib/*:${dir}/plugins/*"
jreDir=`ls -d ${dir}/*jre* 2>/dev/null`

if [ -d "${dir}/../jre.bundle/Contents/Home/bin" ] ; then
    JAVA="${dir}/../jre.bundle/Contents/Home/bin/java"
    CLASSPATH="$dir/lib/$nmrfxlib:$CLASSPATH"
elif [ -d "${dir}/jre/bin" ] ; then
    JAVA="${dir}/jre/bin/java"
    CLASSPATH="$dir/lib/$nmrfxlib:$CLASSPATH"
elif [ -f "${jreDir}/bin/java" ] ; then
    JAVA="${jreDir}/bin/java"
    CLASSPATH="$dir/lib/$nmrfxlib:$CLASSPATH"
else
    if [ -n "$JAVA_HOME" ] ; then
        JAVA="$JAVA_HOME/bin/java"
    fi
    CLASSPATH="$dir/lib/$nmrfxlib:$CLASSPATH"
fi

export CLASSPATH

if [ "$#" -eq 0 ]; then
    exec "$JAVA" -Djava.awt.headless=true -mx${HEAP_MEM}m -cp "$CLASSPATH" $JAVA_OPTS $nvjmain ${1+"$@"}
else
    exec "$JAVA" -Djava.awt.headless=true -mx${HEAP_MEM}m -cp "$CLASSPATH" $JAVA_OPTS $nvjmain -c "import dispatchnvfx" ${1+"$@"}
fi

