import os
from pyproc import *
procOpts(nprocess=1)
FID('../testfids/jeol/indanone_HMBC-1-1.jdf')
CREATE('../../tmp/tst_jeol_hmbc.nv')
fixdsp(True)
label('1H','13C')
sf('X_FREQ','Y_FREQ')
sw('X_SWEEP','Y_SWEEP')
ref('','C')
DIM(1)
SB()
ZF()
FT()
PHASE(ph0=-50.414,ph1=-211.7)
TRIM()
COMB(coef=[1,0,0,1])
DIM(2)
MERGE()
SB(c=0.5)
ZF()
FT(negateImag=False, negatePairs=False)
#SIGN('i')
#RFT(negatePairs=False)
MAG()
run()

