import os
from pyproc import *
procOpts(nprocess=1)
FID('../testfids/jeol/indanone_HMBC-1-1.jdf')
CREATE('../../tmp/tst_jeol_hmbc.nv')
fixdsp(True)
label('1H','13C')
sf('X_FREQ','Y_FREQ')
sw('X_SWEEP','Y_SWEEP')
ref('','C')
DIM(1)
SB()
ZF()
FT()
PHASE(ph0=-50.414,ph1=-211.7)
TRIM()
DIM(2)
SB(c=0.5)
ZF(size=64)
SIGN('i')
RFT(negatePairs=False)
MAG()
REVERSE()
run()

