import os
from dscript import nd
from pyproc import *
from org.nmrfx.processor.datasets.vendor import RS2DData
procOpts(nprocess=7)
FID('../testfids/rs2d/2Dhetero/688')
CREATE('../../tmp/rs2d_2dhetero.nv')
acqOrder('1')
acqarray(0,0)
fixdsp(True)
skip(0,0)
label('1H','1H_2')
acqsize(0,0)
tdsize(0,0)
sf('BASE_FREQ_1','BASE_FREQ_1')
sw('SPECTRAL_WIDTH','SPECTRAL_WIDTH_2D')
ref('','H')
DIM(1)
TDCOMB(coef='echo-antiecho')
SB()
ZF(factor=1)
FT()
PHASE(ph0=-70.5,ph1=-91.2,dimag=False)
DIM(2)
SB(c=0.5)
ZF(factor=2)
FT(negateImag=True)
MAG()
run()
d = nd.open('../../tmp/rs2d_2dhetero.nv')
print d
RS2DData.saveToRS2DFile(d,'data.dat')
