#!/bin/sh

# nmrfxa [ script  [ arg ... ] ]
# 
# optional environment variables:
#
# JAVA_HOME  - directory of JDK/JRE, if not set then 'java' must be found on PATH
# CLASSPATH  - colon separated list of additional jar files & class directories
# JAVA_OPTS  - list of JVM options, e.g. "-Xmx256m -Dfoo=bar"
#
JAVA_OPTS="--add-opens=javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED -Dprism.maxvram=2G"

if [ -n "$NMRFXP_MEMORY" ] ; then
    HEAP_MEM=$NMRFXP_MEMORY
else
    HEAP_MEM="2048"
fi

nvjver=${project.version}
nvjmain=org.nmrfx.analyst.gui.NMRAnalystApp
nmrfxlib="nmrfx-analyst-gui-$nvjver.jar"

JAVA=java

# get the directory path of this script
# resolve script symlink, if any
pgm="$0"
while [ -h "$pgm" ]; do
    ls=`ls -ld "$pgm"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        pgm="$link"
    else
        pgm=`dirname "$PRG"`/"$link"
    fi
done

dir=`dirname "$pgm"`
CLASSPATH="${dir}/lib/*:${dir}/plugins/*"
LOG_CONFIG="-Dlogback.configurationFile=${dir}/config/logback.xml"
jreDir=`ls -d ${dir}/*jre* 2>/dev/null`

if [ -d "${dir}/../jre.bundle/Contents/Home/bin" ] ; then
    JAVA="${dir}/../jre.bundle/Contents/Home/bin/java"
    CLASSPATH="$dir/lib/$nmrfxlib:$CLASSPATH"
elif [ -d "${dir}/jre/bin" ] ; then
    JAVA="${dir}/jre/bin/java"
    CLASSPATH="$dir/lib/$nmrfxlib:$CLASSPATH"
elif [ -f "${jreDir}/bin/java" ] ; then
    JAVA="${jreDir}/bin/java"
    CLASSPATH="$dir/lib/$nmrfxlib:$CLASSPATH"
else
    if [ -n "$JAVA_HOME" ] ; then
        JAVA="$JAVA_HOME/bin/java"
    fi
    CLASSPATH="$dir/lib/$nmrfxlib:$CLASSPATH"
fi

export CLASSPATH
exec "$JAVA" -Xms1024m -Xmx${HEAP_MEM}m -cp "$CLASSPATH" $LOG_CONFIG $JAVA_OPTS $nvjmain ${1+"$@"}
