#!/bin/sh

# nmrfxag [ script  [ arg ... ] ]
# 
# optional environment variables:
#
# JAVA_HOME  - directory of JDK/JRE, if not set then 'java' must be found on PATH
# CLASSPATH  - colon separated list of additional jar files & class directories
# JAVA_OPTS  - list of JVM options, e.g. "-Xmx256m -Dfoo=bar"
#
JAVA_OPTS="--add-opens=javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED"

#            <option>--add-opens</option>
#            <option>javafx.controls/com.sun.javafx.scene.control.behavior=ALL-UNNAMED</option>
#            <option>--add-opens</option>
#            <option>javafx.controls/com.sun.javafx.scene.control.inputmap=ALL-UNNAMED</option>
#            <option>--add-opens</option>
#            <option>javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED</option>


if [ -n "$NMRFXP_MEMORY" ] ; then
    HEAP_MEM=$NMRFXP_MEMORY
else
    HEAP_MEM="2048"
fi

nvjver=${project.version}
nvjmain=org.nmrfx.analyst.gui.NMRAnalystApp
iscygwin=false
ismsys=false
case "`uname`" in
    CYGWIN*) iscygwin=true ;;
    MINGW*) ismsys=true ;;
esac

JAVA=java

# get the directory path of this script
# resolve script symlink, if any
pgm="$0"
while [ -h "$pgm" ]; do
    ls=`ls -ld "$pgm"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        pgm="$link"
    else
        pgm=`dirname "$PRG"`/"$link"
    fi
done

dir=`dirname "$pgm"`
CLASSPATH=${dir}"/lib/Manifest.jar"
jreDir=`ls -d *jre* 2>/dev/null`
if [ -d "${dir}/../jre.bundle/Contents/Home/jre/bin" ] ; then
    JAVA="${dir}/../jre.bundle/Contents/Home/jre/bin/java"
    CLASSPATH="$dir/lib/nmrfx-analyst-gui-$nvjver.jar:$CLASSPATH"
elif [ -d "${dir}/jre/bin" ] ; then
    JAVA="${dir}/jre/bin/java"
    CLASSPATH="$dir/lib/nmrfx-analyst-gui-$nvjver.jar:$CLASSPATH"
elif [ -f "${jreDir}/bin/java" ] ; then
    JAVA="${jreDir}/bin/java"
    CLASSPATH="$dir/lib/nmrfx-analyst-gui-$nvjver.jar:$CLASSPATH"
else
    if [ -n "$JAVA_HOME" ] ; then
        if [ -x "$JAVA_HOME/jre/sh/java"  ] ; then
            # AIX location
            JAVA="$JAVA_HOME/jre/sh/java"
        else
            JAVA="$JAVA_HOME/bin/java"
        fi
    fi

    if $ismsys ; then
        nvjdir=`$dir/echopath "$dir"`
        CLASSPATH="$nvjdir/nmrfx-analyst-gui-$nvjver.jar;$CLASSPATH"
    elif $iscygwin ; then
        CLASSPATH=`cygpath -pu "$CLASSPATH"`
        CLASSPATH="$dir/nmrfx-analyst-gui-$nvjver.jar;$CLASSPATH"
        CLASSPATH=`cygpath -pw "$CLASSPATH"`
    else
        CLASSPATH="$dir/nmrfx-analyst-gui-$nvjver.jar:$CLASSPATH"
    fi
fi

export CLASSPATH
exec "$JAVA" -mx${HEAP_MEM}m -cp "$CLASSPATH" $JAVA_OPTS $nvjmain ${1+"$@"}
