#!/bin/sh

# nmrfxpg [ script  [ arg ... ] ]
# 
# optional environment variables:
#
# JAVA_HOME  - directory of JDK/JRE, if not set then 'java' must be found on PATH
# CLASSPATH  - colon separated list of additional jar files & class directories
# JAVA_OPTS  - list of JVM options, e.g. "-Xmx256m -Dfoo=bar"
#

if [ -n "$NMRFXP_MEMORY" ] ; then
    HEAP_MEM=$NMRFXP_MEMORY
else
    HEAP_MEM="2048"
fi

nvjver=${project.version}
nvjmain=org.nmrfx.processor.gui.MainApp
iscygwin=false
ismsys=false
case "`uname`" in
    CYGWIN*) iscygwin=true ;;
    MINGW*) ismsys=true ;;
esac

JAVA=java

# get the directory path of this script
# resolve script symlink, if any
pgm="$0"
while [ -h "$pgm" ]; do
    ls=`ls -ld "$pgm"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        pgm="$link"
    else
        pgm=`dirname "$PRG"`/"$link"
    fi
done

dir=`dirname "$pgm"`
CLASSPATH=${classpath}

if [ -d "${dir}/../jre.bundle/Contents/Home/jre/bin" ] ; then
    JAVA="${dir}/../jre.bundle/Contents/Home/jre/bin/java"
    CLASSPATH="$dir/lib/processorgui-$nvjver.jar:$CLASSPATH"
elif [ -d "${dir}/jre/bin" ] ; then
    JAVA="${dir}/jre/bin/java"
    CLASSPATH="$dir/lib/processorgui-$nvjver.jar:$CLASSPATH"
else
    if [ -n "$JAVA_HOME" ] ; then
        if [ -x "$JAVA_HOME/jre/sh/java"  ] ; then
            # AIX location
            JAVA="$JAVA_HOME/jre/sh/java"
        else
            JAVA="$JAVA_HOME/bin/java"
        fi
    fi

    if $ismsys ; then
        nvjdir=`$dir/echopath "$dir"`
        CLASSPATH="$nvjdir/processorgui-$nvjver.jar;$CLASSPATH"
    elif $iscygwin ; then
        CLASSPATH=`cygpath -pu "$CLASSPATH"`
        CLASSPATH="$dir/processorgui-$nvjver.jar;$CLASSPATH"
        CLASSPATH=`cygpath -pw "$CLASSPATH"`
    else
        CLASSPATH="$dir/processorgui-$nvjver.jar:$CLASSPATH"
    fi
fi

export CLASSPATH
exec "$JAVA" -mx${HEAP_MEM}m -cp "$CLASSPATH" $JAVA_OPTS $nvjmain ${1+"$@"}
