name: Cleanup

# Controls when the action will run. Triggers the workflow on branch deletion, for any branch
on:
  delete

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cleanup"
  cleanup:
    if: github.event.ref_type == 'branch'

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SUBMODULE_ACCESS_TOKEN }}
          lfs: 'true'
          # Check-out the submodules as well
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'maven'

      - name: Download sharepoint client
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "nanalysis/sharepoint-client"
          version: "tags/v1.3"
          file: "sharepoint-client-1.3-jar-with-dependencies.jar"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete build
        env:
          DELETED_REF: ${{ github.event.ref }}
          SHAREPOINT_CLIENT_ID: ${{ secrets.SHAREPOINT_CLIENT_ID }}
          SHAREPOINT_CLIENT_SECRET: ${{ secrets.SHAREPOINT_CLIENT_SECRET }}
        run: bash .github/workflows/actions-delete-build.sh

